language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: bionic

env:
  - CAKEPHP_VERSION=4.0.*

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer require "cakephp/cakephp:${CAKEPHP_VERSION}" --no-update

install: composer update --prefer-dist --no-interaction

script:
  - if [[ $TRAVIS_PHP_VERSION = 7.3 ]]; then export CODECOVERAGE=1; vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $TRAVIS_PHP_VERSION != 7.3 ]]; then vendor/bin/phpunit; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION = 7.3 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: true
