language: php

php:
#  - 7.1
#  - 7.2
#  - 7.3
  - 7.4

dist: trusty

env:
#  - CAKEPHP_VERSION=3.7.*
  - CAKEPHP_VERSION=3.8.*
  - CAKEPHP_VERSION=4.0.*

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer require "cakephp/cakephp:${CAKEPHP_VERSION}" --no-update

install: composer update --prefer-dist --no-interaction

script:
  - if [[ $TRAVIS_PHP_VERSION != 7.0 ]]; then vendor/bin/phpunit; fi

notifications:
  email: true
