language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

dist: trusty

env:
  - CAKEPHP_VERSION=3.6.* DEFAULT=1

matrix:
  include:
    - php: 5.6
      env: CAKEPHP_VERSION=3.4.*
    - php: 5.6
      env: CAKEPHP_VERSION=3.5.*
    - php: 7.0
      env: CAKEPHP_VERSION=3.4.*
    - php: 7.0
      env: CAKEPHP_VERSION=3.5.*
    - php: 7.1
      env: CAKEPHP_VERSION=3.4.*
    - php: 7.1
      env: CAKEPHP_VERSION=3.5.*
    - php: 7.2
      env: CAKEPHP_VERSION=3.4.*
    - php: 7.2
      env: CAKEPHP_VERSION=3.5.*

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer require "cakephp/cakephp:${CAKEPHP_VERSION}" --no-update

install: composer update --prefer-dist --no-interaction

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.0 ]]; then export CODECOVERAGE=1; vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 ]]; then vendor/bin/phpunit; fi

after_success:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.0 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: true
